package ml.shifu.plugin.encog.adapter;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;

import javax.xml.transform.sax.SAXSource;
import javax.xml.transform.stream.StreamResult;

import org.dmg.pmml.PMML;
import org.jpmml.model.ImportFilter;
import org.jpmml.model.JAXBUtil;
import org.xml.sax.InputSource;

public class BasicAdapterTest {

    public PMML readPMMLFile(String initPmmlPath) {
        try {
            // write PMML
            InputStream is = new FileInputStream(initPmmlPath);
            InputSource source = new InputSource(is);
            // Use SAX filtering to transform PMML schema version 3.X and 4.X
            // documents to PMML schema version 4.2 document
            SAXSource transformedSource = ImportFilter.apply(source);

            PMML pmml = JAXBUtil.unmarshalPMML(transformedSource);
            return pmml;
        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;
    }

    /**
     * This function supports the writeToPMML() method that marshals a PMML
     * model to a PMML file.
     * 
     * @param model
     *            PMML model generated by PMMLAdapter
     * @param path
     *            The PMML file path
     */
    protected void writePMML(String path,PMML pmml) {

        try {
            // write PMML
            OutputStream os = new FileOutputStream(path);
            StreamResult result = new StreamResult(os);
            JAXBUtil.marshalPMML(pmml, result);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

   
}
